CREATE  TABLE SRAA_SAND.TEMP_RMS_TDITW
AS
 (select 
TDHPF.DEST_PO_ID, 
MAX(TMHPF.MKT_PO_ID) AS MKT_PO_ID, 
SUM(TDITW.UN_TXN_INV_QTY) as INV_RCPT_QTY
--,COALESCE(TDHPF.PLN_STK_DT,TMHPF.PLN_STK_DT,CAST('9999-12-31' AS DATE FORMAT 'YYYY-MM-DD')) AS PLN_STK_DT

from  VIEWINV.TDITW_DLY_INV_TXN_FCT TDITW

INNER JOIN VIEWXREF.TDPOX_DEST_PO_XREF TDPOX
ON TDITW.ORD_NBR = TDPOX.ORD_NBR
INNER JOIN VIEWORDER.TDHPF_DEST_HDR_PO_FCT TDHPF
ON TDHPF.DEST_PO_KEY = TDPOX.DEST_PO_KEY

INNER JOIN VIEWORDER.TMHPF_MKT_HDR_PO_FCT TMHPF
ON TMHPF.MKT_PO_KEY = TDHPF.MKT_PO_KEY

where TMHPF.PLN_STK_DT between DATE '2015-04-02' and Date '2016-12-30' 
and TDITW.TXN_TYP_CD = 20 
group by TDHPF.DEST_PO_ID) WITH DATA
PRIMARY INDEX(DEST_PO_ID);